import '../model/list_model.dart';

class ComList {
  static List<ListModel> names = [
    ListModel(name: 'Apple', price: 99, quantity: 1),
    ListModel(name: 'Banana', price: 59, quantity: 2),
    ListModel(name: 'Orange', price: 79, quantity: 1),
    ListModel(name: 'Grapes', price: 129, quantity: 1),
    ListModel(name: 'Strawberry', price: 199, quantity: 1),
    ListModel(name: 'Pineapple', price: 149, quantity: 1),
    ListModel(name: 'Watermelon', price: 199, quantity: 1),
    ListModel(name: 'Mango', price: 89, quantity: 1),
    ListModel(name: 'Peach', price: 109, quantity: 1),
    ListModel(name: 'Pear', price: 79, quantity: 1),
    ListModel(name: 'Kiwi', price: 69, quantity: 1),
    ListModel(name: 'Plum', price: 49, quantity: 1),
    ListModel(name: 'Cherry', price: 159, quantity: 1),
    ListModel(name: 'Blueberry', price: 179, quantity: 1),
    ListModel(name: 'Raspberry', price: 169, quantity: 1),
    ListModel(name: 'Blackberry', price: 139, quantity: 1),
    ListModel(name: 'Lemon', price: 49, quantity: 1),
    ListModel(name: 'Lime', price: 29, quantity: 1),
    ListModel(name: 'Cantaloupe', price: 129, quantity: 1),
    ListModel(name: 'Apricot', price: 89, quantity: 1),
    ListModel(name: 'Coconut', price: 199, quantity: 1),
    ListModel(name: 'Fig', price: 79, quantity: 1),
    ListModel(name: 'Guava', price: 99, quantity: 1),
    ListModel(name: 'Lychee', price: 159, quantity: 1),
    ListModel(name: 'Nectarine', price: 109, quantity: 1),
    ListModel(name: 'Papaya', price: 119, quantity: 1),
    ListModel(name: 'Passion Fruit', price: 169, quantity: 1),
    ListModel(name: 'Persimmon', price: 79, quantity: 1),
    ListModel(name: 'Tangerine', price: 69, quantity: 1),
  ];
}
